[[plugins]]
repo = 'vim-scripts/wombat256.vim'

[[plugins]]
repo = 'vim-scripts/BusyBee'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'jonathanfilip/vim-lucius'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'hail2u/h2u_colorscheme'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'jnurmine/Zenburn'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'ajmwagar/vim-deus'

[[plugins]]
repo = 'twerth/ir_black'

[[plugins]]
repo = 'twerth/ir_black'

[[plugins]]
repo = 'fmoralesc/vim-vitamins'

[[plugins]]
repo = 'vim-scripts/moria'

[[plugins]]
repo = 'vim-scripts/moria'

[[plugins]]
repo = 'vim-scripts/moria'

[[plugins]]
repo = 'chriskempson/tomorrow-theme'

[[plugins]]
repo = 'vim-scripts/Guardian'

[[plugins]]
repo = 'vim-scripts/rdark'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'KnoP-01/tortus'
