[[plugins]]
repo = 'davidhalter/jedi'
on_ft = ['python']
hook_add = '''
let g:jedi#completions_enabled = 0
'''

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']

# markdown
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html']
hook_add = '''
let g:user_emmet_expandabbr_key = '<leader>e'
let g:use_emmet_complete_tag = 1
"set emmet_settings['ja']
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['html', 'markdown']


# javascript/coffee
[[plugins]]
repo = 'vim-scripts/jQuery'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

# yaml
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yaml', 'yml']

# toml
[[plugins]] 
repo = 'cespare/vim-toml'
on_ft = ['toml']
